### ISSUE TITLE
PublishNodes on Command-line creates wrong Redirect URIs

### ISSUE THREAD

**Issue by sbruggmann** [neos/redirecthandler-neosadapter#23]
Given you import a Node "Test A" programmatically to a Workspace "import".
And you publish this nodes in your CommandController or via command-line `flow workspace:publish import`.
Then you import to the same Node again, but with the Title "Test Aa" and again you publish from your CommandController or via command-line.

Expected behaviour:
A Redirect from `en/test-a` to `en/test-aa` is recorded.

Actual behaviour, at least in Neos 3.3:
A Redirect from `./index.php/en/test-a` to `./index.php/en/test-aa` is recorded using `flow server:run`.
A Redirect from `/var/www/neos/en/test-a` to `/var/www/neos/en/test-aa` is recorded in production.

Test CommandController (`flow redirect:test --site-path-segment-name neosdemo`):
https://gist.github.com/sbruggmann/e0b106fc8b148d7cedb8e84a74748ab5

**Comment by kdambekalns** [comment]
You need to set FLOW_REWRITEURLS so Flow knows it can leave out the `index.php`. This is done in "our" `.htaccess` and probably in your production setup as well, but you missed it on CLI.
