### ISSUE TITLE
Leads to broken node moves

### ISSUE THREAD

**Issue by kitsunet** [neos/redirecthandler-neosadapter#30]
Still figuring out the details but having this package in an installation reproducably leads to nodes being lost after moving subtrees. The result of this error will be that after publishing the subtree is back in it's old place while one leaf node is completely lost. Looking at the database reveals it was moved to the correct location but as parents are not in place it is no longer accessible. 

**At this moment I would advise to uninstall the package immediately until the issue is resolved.**

**Comment by davidspiola** [comment]
Hi Christian, I can confirm this behavior but can also not narrow it down to a specific bug. It seems it's somehow related to the amount of nodes you move and in how many sublevels they are.  For me, this leads to the conclusion that this is somehow related to the amount of signals which are fired when you move a lot of nodes.

**Comment by aertmann** [comment]
Have experienced this issue as well a couple times, been able to fix it by fixing the path hashes manually in the database.

**Comment by davidspiola** [comment]
Hi @aertmann, I created this query to identify the borken nodes and moved all dimension variants in a recovery folder (with all child nodes). It's not a solution, but helped me to recovery the missing document nodes. After that I moved them back where they belong.

```
SELECT identifier
FROM (
    SELECT identifier, path
    FROM neos_contentrepository_domain_model_nodedata
    -- WHERE path like '/sites/xxx%' and nodetype = 'type' and workspace = 'live'
    GROUP BY identifier, path
) t
GROUP BY identifier having count(identifier) > 1;"
```

**Comment by kitsunet** [comment]
I am relatively convinced already that it's about reading certain nodes in the redirect package, we might need to just store the information and create the redirects after persisting the publication.

**Comment by kitsunet** [comment]
We cannot switch the signal, you need to know the old position for the redirect ;)

**Comment by gerhard-boden** [comment]
Haha, right 😄  
So we'll need to temporary store the necessary node information somewhere like you suggested on ``beforeNodePublishing`` and ultimately create the redirects on ``nodePublished`` or ``repositoryObjectsPersisted ``. 

We should also consider warning people that reading certain nodes when reacting to signals may cause side effects (if fixing the root cause for this can not be done easily)

**Comment by kitsunet** [comment]
And now comes the worst part, I think it's generating the node URI that is reading the nodes that ultimately breaks it. And we need to generate the node URI before publishing because otherwise it's no longer there...

**Comment by dlubitz** [comment]
Can also confirm this issue. Had this several times, but just for multi-dimensional (multilang) websites. Would love to help reviewing and testing your fix.

**Comment by kitsunet** [comment]
I don't understand those functional tests? Are they supposed to be run with the demo site? Because then I am pretty sure they weren't green before the change?

**Comment by kitsunet** [comment]
yep can confirm, at least I get the same errors in 2.0 branch as well (without my chnages) as well. I am not sure how these tets are supposed to be run.

**Comment by gerhard-boden** [comment]
to be honest I'm not sure if we need that single functional test with those three scenarios (which are partly already tested within the behat tests). Before you waste too much time on fixing that broken test i could also add the two missing "move node" scenarios to the Behat test.

**Comment by aertmann** [comment]
@kitsunet: Hey I assume you're planning to tag a release for this bugfix, if you forgot this is simply a reminder. Thank for finding the cause of this nasty issue and fixing it!
