### ISSUE TITLE
Publish nodes on CLI cause exception during redirect generation

### ISSUE THREAD

**Issue by mwitte** [neos/redirecthandler-neosadapter#41]
Publishing on CLI uses a http request
https://github.com/neos/redirecthandler-neosadapter/blob/1504e8a580ad931e93de0983e50ad426cf568d18/Classes/Service/NodeRedirectService.php#L492

> Call to undefined method Neos\Flow\Cli\CommandRequestHandler::getHttpRequest()
   Type: Error
  File: Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_RedirectHand
        ler_NeosAdapter_Service_NodeRedirectService.php
  Line: 492
neos/neos: 4.3.5
neos/redirecthandler-neosadapter: 4.0.3

I've tried to exclude these nodes of the redirect workflow but the exclusion only happens during the "createPendingRedirects" workflow. The above Error happens before in the "collectPossibleRedirects" workflow.

This is a multi domain and dimensions setup, not sure if this also important. Our usecase is an automatic importer for nodes given by external api. It would be also acceptable if the redirect management ignores the imported nodes.

**Comment by Sebobo** [comment]
I think you should completely turn off the redirect creation during imports. You can do this via the `Settings.yaml` in a custom Context for example.
See https://neos-redirecthandler-adapter.readthedocs.io/en/latest/#restrict-generation

**Comment by mwitte** [comment]
I saw this already but before it collects possible redirects by comparing old and new urls, mentioned the workflow above. I found no option to turn this off in the Settings.yaml :/

**Comment by Sebobo** [comment]
Just had another one asking about this issue. I recommended for now to add a check for `FLOW_SAPITYPE === 'CLI'` to their fork in Package.php or in the methods that cause the issue.

It's possible a first solution would do something similar, but I have to put some thought into it.

**Comment by radmiraal** [comment]
@Sebobo I just ran into it too, I considered the custom context but we're already running in a subcontext on prod, so that would require a rethink of our deployment strategy ;)

What about an environment variable that allows temporal disabling of the redirect feature? Like:

    NEOS_DISABLE_REDIRECTSERVICE=1 ./flow some:command

**Comment by Sebobo** [comment]
@radmiraal you can simply use a env variable in your settings and control it this way :)

**Comment by radmiraal** [comment]
I just tried (by using AOP) if I could get a well crafted uribuilder on the CLI, but I would in that case still be required to set the baseUri in Flow. The uriBuilder always calls the baseUriProvider which will fetch the request itself from the requesthandler. This makes uriBuilding from the CLI with a custom crafted request hard anyway and this might require some changes in Flow. So probably having a simple check to fully disable the redirect handling on CLI or by a flag would be the best way (I like the env replacement setting though... maybe a simple `enable` setting for the whole package would be enough...

**Comment by Sebobo** [comment]
Merged and released the PR from @regniets to allow disabling the behaviour via a setting #42

**Comment by bweinzierl** [comment]
Thanks for this Feature!
What about the usecases where you actually want the redirects to be managed? Say moving Nodes via CLI. I am having this usecase in a project and used baseUri to create a new HttpRequest for the uriBuilder when baseUri is configured. Otherwhise throws an exception to inform about the baseUri need (it is a Neos 4.3 installation)

Would you accept a merge request for that? I could also implement a switch to make it work for newer Neos versions using the serverRequestFactory. But i guess i would have to use the objectManager to retrive the factory as it is not injectable in earlier versions

**Comment by Sebobo** [comment]
That is still possible. Of course it would be great if it works 100% fine at some point whatever you do via cli.

**Comment by Sebobo** [comment]
@bweinzierl were you able to work on the PR?
We could use this in a project.
If not maybe you can share the code and I can mature it there to then create the PR from it.

**Comment by Sebobo** [comment]
OK, I now got funding to implement publishing with redirect creation and will work on it tomorrow.
I'll first focus on making it work for a single site installation and make a PR, if there is time left I will work on multi site support and improving feedback during the publish command somehow.

**Comment by Sebobo** [comment]
With #49 (still a draft) it's now already possible to correctly generate redirects in Neos 5.x with single site installations. Feedback is welcome. I also noted down the still missing pieces.
