### ISSUE TITLE
Hidden document nodes can't be redirected

### ISSUE THREAD

**Issue by jobee** [neos/redirecthandler-neosadapter#46]
**Steps to reproduce**

1.) hide a document node
2.) add a redirect for that uri/path
3.) on request you still get the 404 response

Are there any reasons for that or is it a bug?

Tested with 4.0.3

**Comment by Sebobo** [comment]
See also https://github.com/neos/redirecthandler/issues/39 and https://github.com/neos/redirecthandler/pull/40.

It has to be implemented differently than in the PR and it has to be done in this package.

**Comment by gerhard-boden** [comment]
I have good news, I researched this behavior yesterday and found out that it surprisingly has nothing to do with the redirect package(s) itself. It's a regression introduced within the Neos core package fixed here:
https://github.com/neos/neos-development-collection/pull/2998

**Comment by kdambekalns** [comment]
With #2998 merged I'll close this.
