### ISSUE TITLE
Redirect creation fails with dimension fallbacks

### ISSUE THREAD

**Issue by kdambekalns** [neos/redirecthandler-neosadapter#6]
Given
- a setup with languages 'en' and 'de', having a fallback 'de -> 'en'
- a node existing in 'en' that is changed in 'de'

Now the check for an existing node in `createRedirectsForPublishedNode()` will never find a `$targetNode` and return early.

✅ For a deletion this is fine (for now), as a node visible via fallback cannot be deleted.
❌ For a changed `uriPathSegment` a new node is created but no redirect is set up.
❌ For a moved node a new node is indeed created, but again, no redirect is set up.

**Comment by gerhard-boden** [comment]
Hi @kdambekalns, 
could you please give https://github.com/neos/redirecthandler-neosadapter/pull/7 a try?

I'm afraid the bug is even worse see: https://github.com/neos/redirecthandler-neosadapter/issues/9

**Comment by peterbucher** [comment]
@kdambekalns Can we close this issue now?

**Comment by kdambekalns** [comment]
Good question. I have not checked yet whether #7 fixes this…

**Comment by kdambekalns** [comment]
Huh, that's an old issue… :) Ok, looking into this on a customer request.

**Comment by kdambekalns** [comment]
Ok, generation of redirects works fine for the dimension value it is done, so this is closed. But it isn't done at all for fallbacks. Will take care now.

**Comment by gerhard-boden** [comment]
Haha, @dfeyer just pumped a very old PR of mine (the Behat tests) where this SHOULD be covered
see: 
https://github.com/neos/redirecthandler-neosadapter/pull/8/files#diff-6eaac6b8d9f48054ec96a66d36b5bf1fR63

**Comment by gerhard-boden** [comment]
ah i get it now, we do NOT create redirects for fallbacks? 🤔

**Comment by kdambekalns** [comment]
No…

**Comment by gerhard-boden** [comment]
I think we must be careful here, can really but it in a concrete thought yet, but there might be edge cases when this could lead to unwanted behaviour

**Comment by gerhard-boden** [comment]
Wanna hang out in slack real quick?

**Comment by kdambekalns** [comment]
I think these are the cases we need to cover. In all these cases, action needs to be taken for the affected document _and_ it's children.

**no dimensions exist**

- delete a node -> gone for the changed node
- move a node -> redirect for the changed node
- change uriPathSegment -> redirect for the changed node

**dimension set up, no fallbacks in place**

- delete a node -> gone for the changed node
- move a node -> redirect for the changed node and all variants (since we move nodes together)
- change uriPathSegment -> redirect for the changed node

**dimension set up, fallbacks in place, only "base" variant node exists**

- delete a node -> gone for the changed node and all _possible_ variants
- move a node -> redirect for the changed node and all _possible_ variants
- change uriPathSegment -> redirect for the changed node and all _possible_ variants

In the last scenario, actually existing node variants need to have their data taken into account.

---

Anything else? Once we have that nailed down, we could write tests…

**Comment by gerhard-boden** [comment]
Thanks for writing this up, I have something old and yet unmerged in place here:
https://github.com/neos/redirecthandler-neosadapter/pull/11

But I'm pretty sure it's not covering all described cases, especially when it comes to childnodes.

It's been a long time since I dived into this topic, so excuse me if I need a little to fully get up to speed 🙈

**Comment by gerhard-boden** [comment]
Ah was already late yesterday, I obviously DID take care of the child nodes as well 🙈 
Will review my own changes from two years ago shortly
