### ISSUE TITLE
compatibility with Neos 9 beta 17

### ISSUE THREAD

**Issue by creative-resort** [neos/redirecthandler-neosadapter#84]
Including the package via
```
"neos/neos": "9.0.0-beta17",
"neos/flow": "9.0.0-beta17",
"neos/neos-ui": "9.0.0-beta17",
"neos/contentgraph-doctrinedbaladapter": "9.0.0-beta17",
[…]
"neos/redirecthandler": "^6.0",
"neos/redirecthandler-databasestorage": "*",
"neos/redirecthandler-neosadapter": "^5.0",
"neos/redirecthandler-ui": "^3.0",
```
results in the error:

> > Neos\Flow\Composer\InstallerScripts::postUpdateAndInstall
> Required class "Neos\ContentRepository\Core\Projection\CatchUpHookInterface" could not be loaded properly for reflection from "Neos\RedirectHandler\NeosAdapter\CatchUpHook\DocumentUriPathProjectionHook".
> Possible reasons are:
> 
>  * Requiring non-existent classes
>  * Using non-supported annotations
>  * Class-/filename mismatch.
> 
> The "Neos.Flow.object.includeClasses" setting can be used to include or
> exclude classes from reflection.
> 
>   Type:
> Neos\Flow\Reflection\Exception\ClassLoadingForReflectionFailedException
>   File:
> Packages/Framework/Neos.Flow/Classes/Reflection/Exception/ClassLoadingForRe
>         flectionFailedException.php
>   Line: 24
> 
>   Type: Neos\Flow\Core\Booting\Exception\SubProcessException
>   Code: 1355480641
>   File: Packages/Framework/Neos.Flow/Classes/Core/Booting/Scripts.php
>   Line: 727
though the source for the Class / Interface is installed and available.

**Comment by dlubitz** [comment]
A release of the latest changes to the redirectadapter was outstanding. I've created that release, so the package should now be compatible with neos9-beta17.

https://github.com/neos/redirecthandler-neosadapter/releases/tag/5.0.4
